version: 2
updates:
- package-ecosystem: javascript
  directory: "/apps/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  labels:
    - "npm"
    - "dependencies"
    - "automerge"
- package-ecosystem: javascript
  directory: "/libraries/entities"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  labels:
    - "npm"
    - "dependencies"
    - "automerge"
- package-ecosystem: javascript
  directory: "/sdks/requests"
  schedule: "daily"
    interval: daily
  open-pull-requests-limit: 5
  labels:
    - "npm"
    - "dependencies"
    - "automerge"
