version: 2
updates:
  - package-ecosystem: npm
    directory: "/apps/web"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "automerge"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/packages/entities"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "automerge"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/packages/requests"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "automerge"
    schedule:
      interval: daily
