name: ci
on: [push]

jobs:
  change:
    runs-on: ubuntu-latest
    if: github.event.label.name != 'stage-release'
    name: Change
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: node common/scripts/install-run-rush.js change -v
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - run: node common/scripts/install-run-rush.js check
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js lint
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js test:coverage --verbose
  tag:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Tag
    steps:
      - name: Tag @routerating/requests
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/requests-v"
          root: "packages/requests/package.json"
      - name: Tag @routerating/entities
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/entities-v"
          root: "packages/entities/package.json"
      - name: Tag @routerating/web
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/web-v"
          root: "apps/web/package.json"
